= Migrate Actions

During the build process, different tools handle file assets variously, so your images and other embedded files are not always where they need to be relative to the current procedure.
Migrate actions copy resource files to a temporary/uncommitted directory during the build procedure so they can be readily accessed by subsequent steps.

In addition to designating `action: migrate`, migrate operations require just a few simple settings.

[source,yaml]
.Example config -- Instructing file copies with 'migrate' action
----
- action: migrate
  source: index.adoc
  target: _build/
- action: migrate
  source: assets/images
  target: _build/img
  options:
    inclusive: false
- action: migrate
  source: tmp/{{imported_file}}.adoc
  target: _build/{{portal_path}}/{{imported_file}}.adoc
  options:
    missing: warn
----

The first action step above copies all the files and folders in `assets/images` and adds them to `_build/img`.
It will only recreate the contents of the source directory, not the directory path itself, because the `inclusive:` option is set to `false` (its default value is `true`).
When both the source and target paths are directories and inclusive is `true`, the files are copied to `target/source/`.
When inclusive is `false`, they copy to `target/`.

Individual files must be listed in individual steps, one per step, as in the second step above.

In case of a missing source directory or file to be migrated, the default behavior is to exit the build operation (`missing: exit`).
This can be overridden and the migrate action skipped when the source is missing.
Setting the option `missing: warn` logs a warning to console, and `missing: skip` will only print a warning under `--verbose` operations.
